class_name PlayerStateNames extends Resource

const idle:String = "PlayerStateIdle"
const run:String = "PlayerStateRun"
const jump:String = "PlayerStateJump"
const dash:String = "PlayerStateDash"
const side_attack:String = "PlayerStateSideAttack"
const up_attack:String = "PlayerStateUpAttack"
const down_attack:String = "PlayerStateDownAttack"
const parry:String = "PlayerStateParry"
const strong_attack:String = "PlayerStateStrongAttack"
const fall:String = "PlayerStateFall"
const wall_slide:String = "PlayerStateWallSlide"
const charge:String = "PlayerStateCharge"
const damage:String = "PlayerStateDamage"
const death:String = "PlayerStateDeath"
